title: Manoj Baba
description: Cloud Native, DevOps & Observability Enthusiast
google-analytics-id: "G-5QMT1S3WPL"
url: "https://dmanojbaba.github.io"
permalink: /:title:output_ext
plugins:
  - jekyll-sitemap
exclude:
  - README.md
  - LICENSE
